// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/stat_ort_plugin.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class StatOrtPluginBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StatOrtPluginBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  StatOrtPluginBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// ── String memory management ──────────────────────────────────────────
  /// Every char* returned by a vaani_* function must be freed via this.
  void vaani_string_free(ffi.Pointer<ffi.Char> str) {
    return _vaani_string_free(str);
  }

  late final _vaani_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'vaani_string_free',
      );
  late final _vaani_string_free = _vaani_string_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// ── Pipeline lifecycle ────────────────────────────────────────────────
  /// vad_path and speaker_path may be NULL to disable VAD or diarization.
  ffi.Pointer<VaaniPipeline> vaani_pipeline_init(
    ffi.Pointer<ffi.Char> enc_path,
    ffi.Pointer<ffi.Char> dec_path,
    ffi.Pointer<ffi.Char> vocab_path,
    ffi.Pointer<ffi.Char> vad_path,
    ffi.Pointer<ffi.Char> speaker_path,
    int encoder_threads,
  ) {
    return _vaani_pipeline_init(
      enc_path,
      dec_path,
      vocab_path,
      vad_path,
      speaker_path,
      encoder_threads,
    );
  }

  late final _vaani_pipeline_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VaaniPipeline> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('vaani_pipeline_init');
  late final _vaani_pipeline_init = _vaani_pipeline_initPtr
      .asFunction<
        ffi.Pointer<VaaniPipeline> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  void vaani_pipeline_free(ffi.Pointer<VaaniPipeline> p) {
    return _vaani_pipeline_free(p);
  }

  late final _vaani_pipeline_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VaaniPipeline>)>
      >('vaani_pipeline_free');
  late final _vaani_pipeline_free = _vaani_pipeline_freePtr
      .asFunction<void Function(ffi.Pointer<VaaniPipeline>)>();

  /// ── File transcription ────────────────────────────────────────────────
  /// Transcribe a 16 kHz mono int16 WAV file. Returns full transcript.
  ffi.Pointer<ffi.Char> vaani_pipeline_transcribe(
    ffi.Pointer<VaaniPipeline> p,
    ffi.Pointer<ffi.Char> wav_path,
  ) {
    return _vaani_pipeline_transcribe(p, wav_path);
  }

  late final _vaani_pipeline_transcribePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<VaaniPipeline>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('vaani_pipeline_transcribe');
  late final _vaani_pipeline_transcribe = _vaani_pipeline_transcribePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<VaaniPipeline>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// ── Streaming API ─────────────────────────────────────────────────────
  /// Lifecycle:
  /// 1. vaani_stream_init(pipeline, opt_debug_wav_path) -> state
  /// 2. vaani_stream_push_chunk(state, pcm, 512) repeatedly (one call per
  /// 512-sample frame). Returns NULL until a segment closes; then
  /// returns the formatted transcript line (caller frees).
  /// 3. vaani_stream_flush(state) -> trailing transcript or NULL.
  /// MUST be called before close() to retrieve the final segment.
  /// 4. vaani_stream_close(state) — tears down.
  ///
  /// Calling close() without first calling flush() drops any in-progress
  /// segment.
  ffi.Pointer<VaaniStreamState> vaani_stream_init(
    ffi.Pointer<VaaniPipeline> pipeline,
    ffi.Pointer<ffi.Char> out_wav_path,
  ) {
    return _vaani_stream_init(pipeline, out_wav_path);
  }

  late final _vaani_stream_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<VaaniStreamState> Function(
            ffi.Pointer<VaaniPipeline>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('vaani_stream_init');
  late final _vaani_stream_init = _vaani_stream_initPtr
      .asFunction<
        ffi.Pointer<VaaniStreamState> Function(
          ffi.Pointer<VaaniPipeline>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Push exactly 512 samples of int16 PCM (one Silero VAD frame at 16 kHz).
  /// Returns:
  /// * NULL if no segment closed during this push
  /// * malloc'd string with one or more "[mm:ss.SSS - mm:ss.SSS] [Speaker
  /// N]: ..." lines (newline-terminated) if a segment closed
  ffi.Pointer<ffi.Char> vaani_stream_push_chunk(
    ffi.Pointer<VaaniStreamState> state,
    ffi.Pointer<ffi.Int16> pcm_data,
    int num_samples,
  ) {
    return _vaani_stream_push_chunk(state, pcm_data, num_samples);
  }

  late final _vaani_stream_push_chunkPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<VaaniStreamState>,
            ffi.Pointer<ffi.Int16>,
            ffi.Int,
          )
        >
      >('vaani_stream_push_chunk');
  late final _vaani_stream_push_chunk = _vaani_stream_push_chunkPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<VaaniStreamState>,
          ffi.Pointer<ffi.Int16>,
          int,
        )
      >();

  /// Emit any in-progress segment as final text. Returns NULL if there is
  /// nothing buffered, the buffer is too short to be a real segment, or
  /// decoding failed. Safe to call multiple times — subsequent calls
  /// return NULL.
  ffi.Pointer<ffi.Char> vaani_stream_flush(
    ffi.Pointer<VaaniStreamState> state,
  ) {
    return _vaani_stream_flush(state);
  }

  late final _vaani_stream_flushPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<VaaniStreamState>)
        >
      >('vaani_stream_flush');
  late final _vaani_stream_flush = _vaani_stream_flushPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<VaaniStreamState>)
      >();

  /// Tear down the stream. Call vaani_stream_flush() first if you want the
  /// trailing segment.
  void vaani_stream_close(ffi.Pointer<VaaniStreamState> state) {
    return _vaani_stream_close(state);
  }

  late final _vaani_stream_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VaaniStreamState>)>
      >('vaani_stream_close');
  late final _vaani_stream_close = _vaani_stream_closePtr
      .asFunction<void Function(ffi.Pointer<VaaniStreamState>)>();
}

final class VaaniPipeline extends ffi.Opaque {}

final class VaaniStreamState extends ffi.Opaque {}
